import os
from urllib.parse import urljoin

import _common

def db_path(key, runtime):
    """Generates a database path for a given key.

    This function creates a hashed directory structure to store database
    files, which helps to avoid having too many files in a single
    directory.

    Args:
        key (str): The key to use for generating the path.
        runtime: The runtime environment object.

    Returns:
        str: The full path to the database directory for the given key.
    """
    key_hash = _common.md5(key)
    return os.path.join(runtime.config_data['output_path'], 'db', key_hash[:2], key_hash[2:4], key_hash)

def db_url(key, runtime):
    """Generates a database URL for a given key.

    This function creates a URL that corresponds to the hashed directory
    structure generated by the `db_path` function.

    Args:
        key (str): The key to use for generating the URL.
        runtime: The runtime environment object.

    Returns:
        str: The full URL to the database directory for the given key.
    """
    key_hash = _common.md5(key)
    return _common.urljoin(runtime.config_data['base_url'], 'db', key_hash[:2], key_hash[2:4], key_hash)
